server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mikeygithub/microservicecloud-config.git #GitHub上面的git仓库名字
          force-pull: true #强行拉取
          ignore-local-ssh-settings: true # If true, use property based SSH config instead of file based.
